language: generic
sudo: false
env:
  # Path to 'hadolint' binary
  HADOLINT: "${HOME}/hadolint"

jobs:
  include:
    - stage: linting
      install:
        # Download hadolint binary and set it as executable
        - curl -sL -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.17.2/hadolint-$(uname -s)-$(uname -m)" && chmod 700 ${HADOLINT}
      script:
        # List files which name starts with 'Dockerfile'
        # eg. Dockerfile, Dockerfile.build, etc.
        - git ls-files --exclude='Dockerfile*' --ignored | xargs --max-lines=1 ${HADOLINT}
    - stage: php-version-check
      script:
        - ./check-php-version-availability.sh | grep "Result: OK"

stages:
  - linting
  - php-version-check